---

- name: Install packages
  become: yes
  apt: 
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_apache }}"
  notify: restart apache

- name: Enable Apache mod_rewrite
  become: yes
  apache2_module: 
    name: rewrite
    state: present
  notify: restart apache

# TODO: Add configuration to harden the server (signature off, etc)
