############################
# Configuration variables. #
############################

# Remote user name used in devbox
remote_user: ubuntu

# Location of the projects root
projects_root: "/home/{{ remote_user }}/projects"

# Configuration roles
#
# Configuration of devbox functionality.
#
# Comment out the parameters that are not needed to ensure that roles are not
# included in the project.
#
config_roles:
  - apache
  - php
  - mysql
  - projects

# Projects
# 
# Dictionary to add projects.
# Parameters:
#  domain - string - URL to be used from host machine to access project.
#  docroot - string - the location of the project in devbox. It's syntax 
#    contains {{ remote_user }} to make it box indepedent.
#  db_user - string - the name of the database user to be used (empty for root)
#  db_pass - string - the passwrd of the database user to be used (empty for 
#    root)
#  db_name - string - the database name to be used (if empty database is 
#    skipped)
#  tech
projects:
  - { domain: "devbox.local", project: "{{ projects_root}}/test", docroot: "", db_user: "tassos", db_pass: "tassos", db_name: "tassos", tech: "" }
  - { domain: "d8.demo", project: "{{ projects_root }}/D8/00-DEMO", docroot: "tech/web", db_user: "", db_pass: "", db_name: "d8demo", tech: "drupal"}
