---

########################################
# Provision a linux box automatically. #
########################################

- hosts: all
  remote_user: vagrant

  tasks:
    - name: Update apt
      sudo: yes
      apt: update_cache=yes cache_valid_time=8400

    - name: Include variables
      include_vars: variables.yml
      
    - name: Create ~/bin directory
      file:
        path: "~/bin"
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0775

    - name: Install packages
      sudo: yes
      apt: name={{ item }} state=present
      with_items: packages
      notify: restart apache

    - name: Install composer
      shell: "curl -sS https://getcomposer.org/installer | php"
      args:
        creates: "~/bin/composer"

    - name: Move composer to home bin
      shell: "mv composer.phar ~/bin/composer"
      args:
        creates: "~/bin/composer"

    - name: Install drush
      sudo_user: vagrant
      shell: "~/bin/composer global require drush/drush:dev-master"
      args:
        creates: "~/.composer/vendor/bin/drush"

    - name: Update PATH in .profile
      lineinfile:
        dest: "~/.profile"
        regexp: "PATH"
        line: "\\tPATH=\"$HOME/.composer/vendor/bin:$HOME/bin:$PATH\""
        backup: yes

    - name: Create MySQL root password
      command: /usr/bin/openssl rand -base64 16
      register: mysql_root_pass

    # Uncomment the value below to see what is the root password that is
    # generated. This password are written in ~/.my.cnf so you can have a
    # look there after the provisioning of the server.
    #- debug: var=mysql_root_pass

    - name: Update MySQL root password
      mysql_user:
        name: "root"
        host: "{{ item }}"
        password: "{{ mysql_root_pass.stdout }}"
        state: present
      with_items:
          - 127.0.0.1
          - ::1
          - localhost
      notify: restart mysql

    - name: Move my.cnf on ~
      template:
        src: my.cnf.j2
        dest: "~/.my.cnf"
        mode: 0600

    - name: Create database for drupal development
      mysql_db: name="{{ db_name }}" state=present

    - name: Add database users and privileges
      mysql_user:
        name: "{{ db_user }}"
        host: localhost
        password: "{{ db_pass }}"
        priv: "{{ db_name }}.*:ALL,GRANT"
        state: present
    
  handlers:
    - name: restart apache
      sudo: yes
      service: name=apache2 state=restarted
    - name: restart mysql
      sudo: yes
      service: name=mysql state=restarted
