---

##########################################
# Provision a LAMP server automatically. #
##########################################

- hosts: all
  remote_user: "{{ remote_user }}"
  vars_files:
    - config.yml
  gather_facts: yes

  roles:
    - common
  
  tasks:
  - name: Include roles
    include_role:
      name: "{{ roles }}"
    with_items:
      - "{{ config_roles }}"
    loop_control:
      loop_var: "roles"
