---

##########################################
# Provision a LAMP server automatically. #
##########################################

- hosts: all
  remote_user: "{{ remote_user }}"
  vars_files:
    - variables.yml
  gather_facts: yes

  roles:
    - common
    - php
    - apache
    - mysql
