---

##########################################
# Provision a LAMP server automatically. #
##########################################

- hosts: all
  remote_user: ubuntu
  vars_files:
    - variables.yml
  gather_facts: yes

  roles:
    - common
    - php
    # - apache
    # - mysql

