---

- name: Update apt
  become: yes
  apt: 
    update_cache: yes 
    cache_valid_time: 8400

- name: Install utilities
  become: yes
  apt: 
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_utils }}"

- name: Create ~/bin directory
  file:
    path: "~/bin"
    state: directory
    mode: 0775

- name: Add ~/bin to PATH
  lineinfile:
    dest: "~/.profile"
    regexp: "PATH"
    line: "PATH=\"$HOME/bin:$PATH\""
    backup: yes

- name: Add user RSA key
  copy:
    src: "{{ rsa_key }}"
    dest: "~/.ssh/id_rsa"
    mode: 0400

- name: Add SSH config
  copy:
    src: ssh_config
    dest: "~/.ssh/config"
    backup: yes

- name: Add Github fingerprint to known_hosts file
  shell: "ssh-keyscan -H github.com >> ~/.ssh/known_hosts"
  args:
    creates: "~/.ssh/known_hosts"

