---

- name: Update xdebug config file
  blockinfile:
    path: "{{ php_config_dir }}/mods_available/xdebug.ini"
    block: |
      xdebug.remote_enable=1
      xdebug.remote_port=9000
      xdebug.remote_handle=dbgp
      xdebug_remote_connect_back=1
    state: present
    backup: yes
